### ISSUE TITLE
users/suggestions slug language 

### ISSUE THREAD

**Issue by aisayko** [sixohsix/twitter#286]
I have not found a way how to access members of Twitter class in case if member is non english.

For example to find users suggestions in English we must call next resource:
https://api.twitter.com/1.1/users/suggestions/twitter.json

    t.users.suggestions.twitter(lang='en')

But in case of russian lang we must call:
https://api.twitter.com/1.1/users/suggestions/твиттер.json

     t.users.suggestions.???(lang='ru')

So how to access this through  members of Twitter class?

**Comment by RouxRC** [comment]
Hi @aisayko
The slug argument needs to be a category among those predefined by twitter, they always are regular characters, you can access the list of possible values for russian language using first https://api.twitter.com/1.1/users/suggestions.json :
<pre>
 t.users.suggestions(lang='ru')
</pre>

**Comment by aisayko** [comment]
Hi @RouxRC,

> access the list of possible values for russian language 

Yes, and values for category **slug** are in russian language, example response:

    [{u'slug': u'\u043d\u043e\u0432\u043e\u0441\u0442\u0438', u'name': u'\u043d\u043e\u0432\u043e\u0441\u0442\u0438', u'size': 11}, and more...]

So to get list of users i must call:

    t.users.suggestions.**category_slug**(lang='ru')

which is impossible with russian language because **category_slug** is russian.

I'm also tried this approach:

    getattr(t.users.suggestions, 'твиттер')(lang='ru')

And get next error:

    /lib/python2.7/site-packages/twitter/api.py:196: UnicodeWarning: Unicode equal comparison failed to     convert both arguments to Unicode - interpreting them as being unequal
      if k == "_":
    Traceback (most recent call last):
     File "<stdin>", line 1, in <module>
     File "/home/aisayko/devel/venv/botstrap/local/lib/python2.7/site-packages/twitter/api.py", line 203, in     __call__
    uri = build_uri(self.uriparts, kwargs)
    File "/home/aisayko/devel/venv/botstrap/local/lib/python2.7/site-packages/twitter/api.py", line 152, in     build_uri
    if uripart.startswith("_"):
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xd1 in position 0: ordinal not in range(128)

**Comment by RouxRC** [comment]
Hi again!
Mmm indeed, didn't think to try it out...
I've just spent a bit of time investigating it.
This twitter library has a way of calling such api routes using ._(), for instance:
<pre>
 t.users.suggestions._('твиттер')(lang='ru')
</pre>

Although, this also crashes, due to ascii/unicode combinations when building the uri, and I don't feel confident having border effects modifying the bit of code responsible for this, so here's a workaround that seems to do the trick : use urllib.quote to encode your variable so it will be properly set in the request url :
<pre>
 t.users.suggestions._(urllib.quote('твиттер'))(lang='ru')
</pre>

**Comment by aisayko** [comment]
It work now, thanks @RouxRC !
