### ISSUE TITLE
324 Error when trying to update statuses with media_id

### ISSUE THREAD

**Issue by AshBT** [sixohsix/twitter#293]
Referencing this:
https://twittercommunity.com/t/the-validation-of-media-ids-failed-error-code-324/29304/34

This doesn't work:
t.statuses.update(status="PTT ★", media_ids=",".join([id_img1, id_img2]))

This does:
t.statuses.update(status="PTT ★", media_id_string=",".join([id_img1, id_img2]))

**Comment by RouxRC** [comment]
mmm, have you tried this? What I read in the thread is you should take the media_id_string from  the results when uploading, not change the argument used to send the ids of the images

**Comment by AshBT** [comment]
yeah, that was the only thing that worked.  It was simply changing media_id
to media_id_string in the arguments...  I thought I'd pass it along.
ᐧ

On Wed, Jun 3, 2015 at 3:36 AM, Benjamin Ooghe-Tabanou <
notifications@github.com> wrote:

> mmm, have you tried this? What I read in the thread is you should take the
> media_id_string from the results when uploading, not change the argument
> used to send the ids of the images
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sixohsix/twitter/issues/293#issuecomment-108232002>.
>



-- 
Ashley Beattie

**Comment by RouxRC** [comment]
I'm sorry but again this does not make any sense, so I've just tried : of course the second one works, except the resulting twet does not contain any image since media_id_string is not a valid argument for Twitter's statuses/update method (cf https://dev.twitter.com/rest/reference/post/statuses/update )

The correct argument is media_ids

The error described in the twitter forum you are linking is clear: it's safer to take media_id_string field rather than media_id from the output json of the uploading requests, but the status sending should not change at all. I'm updating the readme accordingly.

**Comment by RouxRC** [comment]
PS: and the possible error described in the forum only relates to some bad languages that cannot handle integers that big. In python there's no issue, so media_id and media_id_string in the output json from upload are actually always the same, making this whole report a bit pointless here :)

**Comment by AshBT** [comment]
Hey,
My bad, I'd put it in as media_id, not media_ids.

Thanks for getting back to us so quickly
ᐧ

On Wed, Jun 3, 2015 at 10:33 AM, Benjamin Ooghe-Tabanou <
notifications@github.com> wrote:

> PS: and the possible error described in the forum only relates to some bad
> languages that cannot handle integers that big. In python there's no issue,
> so media_id and media_id_string in the output json from upload are actually
> always the same, making this whole report a bit pointless here :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sixohsix/twitter/issues/293#issuecomment-108457435>.
>



-- 
Ashley Beattie
