### ISSUE TITLE
404 Error while attempting to send a direct message?

### ISSUE THREAD

**Issue by BrightBotTeam** [sixohsix/twitter#307]
Getting an error (pasted at http://pastebin.com/33Pn8Q9x ) while trying to get a bot I'm working on to send a direct message (in reply to a direct message he recieves). I have removed all of the keys and identifying information from the message, but otherwise it is changed. Is the problem in something that I'm passing? I know I had been getting a different error message when trying to send the DM before. I don't think it's something in my code (though if you need to see it, the current full code minus this library is on my profile or at https://github.com/BrightBotTeam/BrightBot ). If you have any insights, let me know. It's highly possible it's just me being a moron, but if so, I have no idea what it is specifically.

Thanks for working on this, btw. Saved me a ton of heartache trying to work with raw REST API.

**Comment by sixohsix** [comment]
Hmm, I suspect you're using the wrong parameters. Right here: https://github.com/BrightBotTeam/BrightBot/blob/master/BrightBotCore.py#L401

You're using "user" as a parameter, but ![according to the docs](https://dev.twitter.com/rest/reference/post/direct_messages/new) you should use either `screen_name` or `user_id`.

Weird that it gives you a 404 error instead of something more useful. Try changing that and let me know if it works.

**Comment by BrightBotTeam** [comment]
Huh, I would have thought it was the same to get as to call. I'll change that and test it once I get the chance.

**Comment by BrightBotTeam** [comment]
Nope, it didn't work, sadly. This time, the error it raised was http://pastebin.com/vvkFPdu8 , the only difference of which I can see is switching the order that the error code displays code vs text.
