### ISSUE TITLE
returned data of oembed is limited

### ISSUE THREAD

**Issue by donnut** [sixohsix/twitter#316]
Maybe it is the whole idea of `oembed`, but the call
```
twitter_api.statuses.oembed(_id=item_id)
```
returns a limited number of keys:

```
{
	"_id" : ObjectId("56656ee656180c7bbb84866b"),
	"provider_url" : "https://twitter.com",
	"version" : "1.0",
	"url" : "https://twitter.com/FlikFluimsnor/statuses/670014207656620032",
	"author_name" : "FlikFluimsnor",
	"height" : null,
	"width" : 550,
	"html" : "<blockquote class=\"twitter-tweet\"><p lang=\"nl\" dir=\"ltr\">Opvang 100 vluchtelingen voor 10 dagen kost gemeente een ton <a href=\"https://t.co/jPtYBytZRA\">https://t.co/jPtYBytZRA</a> Betaald van uw onroerendezaakbelasting</p>&mdash; René Dercksen (@ReneDercksen) <a href=\"https://twitter.com/ReneDercksen/status/670011598942117889\">November 26, 2015</a></blockquote>\n<script async src=\"//platform.twitter.com/widgets.js\" charset=\"utf-8\"></script>",
	"author_url" : "https://twitter.com/FlikFluimsnor",
	"provider_name" : "Twitter",
	"cache_age" : "3153600000",
	"type" : "rich"
}
```
It this the expected reponse? If so, I do I get the full twitter reponse as mentioned in the [docs](https://dev.twitter.com/rest/reference/get/statuses/show/%3Aid)

**Comment by RouxRC** [comment]
Don't understand your question:
- if you want all fields from the API, why do you call the oembed route instead of the "show" one which you are giving the link to? ```twitter_api.statuses.show(_id=item_id)``` seems to be what you're looking for
- otherwise if you want to adjust what oembed returns, see the list of arguments of the statuses/oembed function on the related documentation here: https://dev.twitter.com/rest/reference/get/statuses/oembed

**Comment by donnut** [comment]
Thanks. I misunderstood `oembed`. I thought it was doing what `show` does.
