### ISSUE TITLE
get 404 error when using TwitterStream

### ISSUE THREAD

**Issue by Larryrun80** [sixohsix/twitter#363]
Hi, I'm new using your package.

I'm using TwitterStream class but always receive a 404 error: 

details: {'errors': [{'message': 'Sorry, that page does not exist', 'code': 34}]} 

The same settings works well in Twitter class.

code:
`
ts = TwitterStream(auth=OAuth(settings['access_token'],
                                    settings['access_token_secret'],
                                    settings['consumer_key'],
                                    settings['consumer_secret']))
iterator = ts.statuses.sample()
`
 please check this

And I found Twitter Class will cut message text if its too long and replace with '...'?
Any other way to get the entire text？ Also not found where is the image url in tweet.

**Comment by RouxRC** [comment]
I don't really understand your stream problem, i've just tried to run exactly the same code with my credentials and it works fine. Did you install via pip? are you certain you're using the proper settings?

Regarding tweets being cut, it might be because you're not using the argument "tweet_mode=extended", see this page for more explanations: https://dev.twitter.com/overview/api/upcoming-changes-to-tweets

Regarding images urls, twitter does not return them directly inside the text of a tweet, but instead gives urls such as twitter.com/USER/statuses/ID/photo/1 You need to collect it from the entities or extended_entities fields of each tweet.

**Comment by Larryrun80** [comment]
Hi RouxRC, 
Thanks very much for reply, I should read twitter's guide carefully.
I tried stream class just now and found it works fine. I do adjust some code but seems nothing changed this part, a little wired...  Maybe its caused by some of my mistakes？ under too much pressure these days @_@
I will continue keep an eye on this issue, and report if I find the reason.

Thanks very much for this great job, I tried some package and this is the best.
