### ISSUE TITLE
Support for premium (30day) search

### ISSUE THREAD

**Issue by inactivist** [sixohsix/twitter#373]
Checking the docs for [premium search](https://developer.twitter.com/en/docs/tweets/search/api-reference/premium-search.html#DataEndpoint), it appears to use this endpoint:

`POST /search/30day`

I can't see a way to reference this endpoint using the `Twitter` API class, since `Twitter.search.30day()` is invalid Python syntax. 

Can anyone suggest a clean solution to this?

**Comment by RouxRC** [comment]
Ah, good one! :)
My best guess would be to allow to call these rare new routes with getitem instead of getattr by adding to TwitterCall a __getitem__ function very similar to the __getattr__ one https://github.com/sixohsix/twitter/blob/master/twitter/api.py#L195-L208
@sixohsix any better idea?

Also I fear the /tweets/search/30day/:label/counts routes might not be doable in the current state of the code

**Comment by sixohsix** [comment]
Twitter().tweets.search._("30day")._("whatever_label").counts

Something like that should work.

On Dec 23, 2017 9:13 PM, "Benjamin Ooghe-Tabanou" <notifications@github.com>
wrote:

Ah, good one! :)
My best guess would be to allow to call these rare new routes with getitem
instead of getattr by adding to TwitterCall a *getitem* function very
similar to the *getattr* one https://github.com/sixohsix/
twitter/blob/master/twitter/api.py#L195-L208
@sixohsix <https://github.com/sixohsix> any better idea?

Also I fear the /tweets/search/30day/:label/counts routes might not be
doable in the current state of the code

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/sixohsix/twitter/issues/373#issuecomment-353745768>,
or mute
the thread

**Comment by RouxRC** [comment]
Ah indeed, forgot about the magical _ attribute! :)

**Comment by inactivist** [comment]
> Twitter().tweets.search._("30day")._("whatever_label").counts
>
> Something like that should work.

That seems to work.  Closing this issue for now.  

Thanks for the prompt response, @sixohsix
